# =============================================================================
# getit/settings.py — CONFIGURAÇÕES GERAIS DO PROJETO (🔹 só reconhecer)
# Apps instalados, banco de dados, DEBUG, hosts, arquivos estáticos...
# Na pasta da prova: DEBUG = True + SQLite (pedido da professora).
# 📖 README_1B.md → "Diferença entre a pasta da prova e o repositório",
#                   Parte 3 (PostgreSQL) e Parte 4 (Deploy)
# =============================================================================
"""
Django settings for getit project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import dj_database_url   # usado só no deploy (lê o banco como link). 📖 README_1B → Parte 4

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ll93r_-z#xcsq@ry0nre@@da9z8h%#vo8l)nq$hex2yo*7bx6%"

# SECURITY WARNING: don't run with debug turned on in production!
# PROVA: True → erro aparece completo (página amarela no navegador + traceback no terminal).
# No repositório/deploy está False (segurança). 📖 README_1B → Parte 4
DEBUG = True

# Endereços pelos quais o site aceita ser acessado (NÃO define a porta).
# Com DEBUG = True, localhost já é aceito sozinho. 📖 README_1B → Parte 0 → "Onde fica a porta 8000?"
ALLOWED_HOSTS = ['tecweb-2026-2-projeto1b-so8f.onrender.com', 'localhost', '127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    "notes.apps.NotesConfig",   # ← o NOSSO app. É assim que o Django sabe que o app notes existe
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',   # deploy: serve CSS/JS em produção. 📖 README_1B → Parte 4
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",   # exige {% csrf_token %} em todo form POST (senão 403)
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "getit.urls"   # primeiro arquivo de rotas que o Django lê. 📖 README_1B → Parte 0

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,   # procura templates na pasta templates/ de cada app → notes/templates/
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "getit.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# ---- BANCO DO DEPLOY (Render / PostgreSQL) — comentado na pasta da prova ----
# 📖 README_1B → Parte 4
#DATABASES = {
#    'default': dj_database_url.config(
#        default='postgresql://getit_7u3i_user:WlAmBzQFbuvPWwAKIT1pLMerM5l0ZLP0@dpg-daki95bm8hqs73emo6rg-a.oregon-postgres.render.com/getit_7u3i',
#        conn_max_age=600,
#        ssl_require=not DEBUG
#    )
#}

# ---- BANCO DA PROVA: SQLite, um arquivo só (db.sqlite3) ----
# makemigrations/migrate na prova alteram só este arquivo local.
# 📖 README_1B → Parte 3 (versão PostgreSQL com Docker)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"   # {% static %} gera caminhos começando com /static/
STATIC_ROOT = BASE_DIR / 'staticfiles'   # deploy: onde o collectstatic junta os estáticos


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
