# Generated by Django 6.1 on 2026-09-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_tag_note_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                ("resposta_correta", models.BooleanField()),
            ],
        ),
    ]
