# Generated by Django 6.1 on 2026-09-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_pergunta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField()),
            ],
        ),
    ]
