# Generated by Django 6.1 on 2026-09-28 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="pergunta",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notes.categoria",
            ),
        ),
    ]
